[project]
name = "ai-agent-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "jq>=1.10.0",
    "loadenv>=0.1.1",
    "markdown>=3.9",
    "openai-agents>=0.3.2",
    "pydantic>=2.11.9",
]
